import type { TempleRecord } from "./types.js";
import { portalLabelAndHost } from "./temples.repository.js";

type SeedRow = Omit<TempleRecord, "subdomain" | "portalHost">;

/** Demo temple rows for `npm run seed` only — not applied on server start or migrate. */
const SEED_TEMPLES_CORE: SeedRow[] = [
  {
    tenantId: "f0001001-0001-4001-8001-000000000001",
    name: "Shiva Mandffir London",
    slug: "shiva-mandir-london.omkaarya.com",
    countryCode: "GB",
    countryFlag: "🇬🇧",
    city: "London",
    plan: "Aaradhana",
    devotees: 1200,
    status: "Active",
    compliance: "Verified",
    adminEmail: "admin@shivalondon.org",
  },
  {
    tenantId: "f0001002-0001-4001-8001-000000000002",
    name: "Sri Venkateswara Temple",
    slug: "svt-birmingham.pepulux.app",
    countryCode: "GB",
    countryFlag: "🇬🇧",
    city: "Birmingham",
    plan: "Sankalpa",
    devotees: 890,
    status: "Trial",
    compliance: "Pending",
    adminEmail: "temple@svtb.org",
  },
  {
    tenantId: "f0001003-0001-4001-8001-000000000003",
    name: "Ganesha Temple NYC",
    slug: "ganesha-nyc.omkaarya.com",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "New York",
    plan: "Prarambha",
    devotees: 3400,
    status: "Active",
    compliance: "Verified",
    adminEmail: "office@ganeshanyc.org",
  },
  {
    tenantId: "f0001004-0001-4001-8001-000000000004",
    name: "Durga Mata Seva",
    slug: "durga-seva.omkaarya.com",
    countryCode: "IN",
    countryFlag: "🇮🇳",
    city: "Hyderabad",
    plan: "Free",
    devotees: 210,
    status: "Suspended",
    compliance: "Not set up",
    adminEmail: "contact@durgaseva.in",
  },
  {
    tenantId: "f0001005-0001-4001-8001-000000000005",
    name: "Hanuman Dham",
    slug: "hanuman-dham.omkaarya.com",
    countryCode: "IN",
    countryFlag: "🇮🇳",
    city: "Delhi",
    plan: "Aaradhana",
    devotees: 5600,
    status: "Active",
    compliance: "Verified",
    adminEmail: "admin@hanumandham.in",
  },
  {
    tenantId: "f0001006-0001-4001-8001-000000000006",
    name: "Murugan Temple Sydney",
    slug: "murugan-sydney.pepulux.app",
    countryCode: "AU",
    countryFlag: "🇦🇺",
    city: "Sydney",
    plan: "Sankalpa",
    devotees: 720,
    status: "Active",
    compliance: "Pending",
    adminEmail: "info@murugansydney.au",
  },
  {
    tenantId: "f0001007-0001-4001-8001-000000000007",
    name: "ISKCON Community Hub",
    slug: "iskcon-hub.omkaarya.com",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Los Angeles",
    plan: "Aaradhana",
    devotees: 9800,
    status: "Trial",
    compliance: "Not set up",
    adminEmail: "la@iskcon.example",
  },
  {
    tenantId: "f0001008-0001-4001-8001-000000000008",
    name: "Lakshmi Narayan Mandir",
    slug: "lnm-toronto.omkaarya.com",
    countryCode: "CA",
    countryFlag: "🇨🇦",
    city: "Toronto",
    plan: "Prarambha",
    devotees: 1500,
    status: "Active",
    compliance: "Verified",
    adminEmail: "secretary@lnmtoronto.ca",
  },
  {
    tenantId: "f0001009-0001-4001-8001-000000000009",
    name: "Sai Baba Sansthan",
    slug: "sai-sansthan.omkaarya.com",
    countryCode: "IN",
    countryFlag: "🇮🇳",
    city: "Pune",
    plan: "Sankalpa",
    devotees: 420,
    status: "Suspended",
    compliance: "Pending",
    adminEmail: "trust@saisansthan.in",
  },
  {
    tenantId: "f000100a-0001-4001-8001-00000000000a",
    name: "Radha Krishna Vihar",
    slug: "rkv-dubai.pepulux.app",
    countryCode: "AE",
    countryFlag: "🇦🇪",
    city: "Dubai",
    plan: "Aaradhana",
    devotees: 2300,
    status: "Active",
    compliance: "Verified",
    adminEmail: "admin@rkdubai.ae",
  },
  {
    tenantId: "f000100b-0001-4001-8001-00000000000b",
    name: "Kali Bari Singapore",
    slug: "kali-bari-sg.omkaarya.com",
    countryCode: "SG",
    countryFlag: "🇸🇬",
    city: "Singapore",
    plan: "Free",
    devotees: 180,
    status: "Trial",
    compliance: "Not set up",
    adminEmail: "committee@kalibari.sg",
  },
  {
    tenantId: "f000100c-0001-4001-8001-00000000000c",
    name: "Vishnu Temple Berlin",
    slug: "vishnu-berlin.omkaarya.com",
    countryCode: "DE",
    countryFlag: "🇩🇪",
    city: "Berlin",
    plan: "Prarambha",
    devotees: 640,
    status: "Active",
    compliance: "Pending",
    adminEmail: "vorstand@vishnubeaiwoxdjaoidjaorlin.de",
  },
];

export const SEED_TEMPLES: TempleRecord[] = SEED_TEMPLES_CORE.map((t) => {
  const ph = portalLabelAndHost(t.slug, null);
  return { ...t, subdomain: ph.subdomain, portalHost: ph.portalHost };
});
