import type { TempleRecord } from "./types.js";

/** Seed data for `npm run seed` (PostgreSQL `temples` table). */
export const SEED_TEMPLES: TempleRecord[] = [
  {
    tenantId: "1001",
    name: "Shiva Mandffir London",
    slug: "shiva-mandir-london.omkaarya.com",
    countryCode: "GB",
    countryFlag: "🇬🇧",
    city: "London",
    plan: "Aaaradhana",
    devotees: 1200,
    status: "Active",
    compliance: "Verified",
    adminEmail: "admin@shivalondon.org",
  },
  {
    tenantId: "1002",
    name: "Sri Venkateswara Temple",
    slug: "svt-birmingham.pepulux.app",
    countryCode: "GB",
    countryFlag: "🇬🇧",
    city: "Birmingham",
    plan: "Sankalpa",
    devotees: 890,
    status: "Trial",
    compliance: "Pending",
    adminEmail: "temple@svtb.org",
  },
  {
    tenantId: "1003",
    name: "Ganesha Temple NYC",
    slug: "ganesha-nyc.omkaarya.com",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "New York",
    plan: "Mandala",
    devotees: 3400,
    status: "Active",
    compliance: "Verified",
    adminEmail: "office@ganeshanyc.org",
  },
  {
    tenantId: "1004",
    name: "Durga Mata Seva",
    slug: "durga-seva.omkaarya.com",
    countryCode: "IN",
    countryFlag: "🇮🇳",
    city: "Hyderabad",
    plan: "Free",
    devotees: 210,
    status: "Suspended",
    compliance: "Not set up",
    adminEmail: "contact@durgaseva.in",
  },
  {
    tenantId: "1005",
    name: "Hanuman Dham",
    slug: "hanuman-dham.omkaarya.com",
    countryCode: "IN",
    countryFlag: "🇮🇳",
    city: "Delhi",
    plan: "Aaaradhana",
    devotees: 5600,
    status: "Active",
    compliance: "Verified",
    adminEmail: "admin@hanumandham.in",
  },
  {
    tenantId: "1006",
    name: "Murugan Temple Sydney",
    slug: "murugan-sydney.pepulux.app",
    countryCode: "AU",
    countryFlag: "🇦🇺",
    city: "Sydney",
    plan: "Sankalpa",
    devotees: 720,
    status: "Active",
    compliance: "Pending",
    adminEmail: "info@murugansydney.au",
  },
  {
    tenantId: "1007",
    name: "ISKCON Community Hub",
    slug: "iskcon-hub.omkaarya.com",
    countryCode: "US",
    countryFlag: "🇺🇸",
    city: "Los Angeles",
    plan: "Aaaradhana",
    devotees: 9800,
    status: "Trial",
    compliance: "Not set up",
    adminEmail: "la@iskcon.example",
  },
  {
    tenantId: "1008",
    name: "Lakshmi Narayan Mandir",
    slug: "lnm-toronto.omkaarya.com",
    countryCode: "CA",
    countryFlag: "🇨🇦",
    city: "Toronto",
    plan: "Mandala",
    devotees: 1500,
    status: "Active",
    compliance: "Verified",
    adminEmail: "secretary@lnmtoronto.ca",
  },
  {
    tenantId: "1009",
    name: "Sai Baba Sansthan",
    slug: "sai-sansthan.omkaarya.com",
    countryCode: "IN",
    countryFlag: "🇮🇳",
    city: "Pune",
    plan: "Sankalpa",
    devotees: 420,
    status: "Suspended",
    compliance: "Pending",
    adminEmail: "trust@saisansthan.in",
  },
  {
    tenantId: "1010",
    name: "Radha Krishna Vihar",
    slug: "rkv-dubai.pepulux.app",
    countryCode: "AE",
    countryFlag: "🇦🇪",
    city: "Dubai",
    plan: "Aaaradhana",
    devotees: 2300,
    status: "Active",
    compliance: "Verified",
    adminEmail: "admin@rkdubai.ae",
  },
  {
    tenantId: "1011",
    name: "Kali Bari Singapore",
    slug: "kali-bari-sg.omkaarya.com",
    countryCode: "SG",
    countryFlag: "🇸🇬",
    city: "Singapore",
    plan: "Free",
    devotees: 180,
    status: "Trial",
    compliance: "Not set up",
    adminEmail: "committee@kalibari.sg",
  },
  {
    tenantId: "1012",
    name: "Vishnu Temple Berlin",
    slug: "vishnu-berlin.omkaarya.com",
    countryCode: "DE",
    countryFlag: "🇩🇪",
    city: "Berlin",
    plan: "Mandala",
    devotees: 640,
    status: "Active",
    compliance: "Pending",
    adminEmail: "vorstand@vishnubeaiwoxdjaoidjaorlin.de",
  },
];
