import { z } from "zod";

export const loginBodySchema = z
  .object({
    email: z.string().email(),
    password: z.string().optional(),
    tempPassword: z.string().optional(),
  })
  .refine(
    (d) => {
      const p = (d.password ?? "").trim();
      const t = (d.tempPassword ?? "").trim();
      return p.length > 0 || t.length > 0;
    },
    { message: "Password is required", path: ["password"] }
  );

export const setPasswordBodySchema = z.object({
  email: z.string().email(),
  tempPassword: z.string().min(1),
  newPassword: z.string().min(8),
});

/**
 * Create a super-admin user record.
 * Protected by SUPER_ADMIN_REGISTER_TOKEN (header x-super-admin-register-token).
 */
export const superAdminRegisterBodySchema = z
  .object({
    email: z.string().email(),
    /**
     * If provided (or generated by server), the user can sign in via temp password on /api/login.
     * If permanentPassword is provided, tempPassword is optional.
     */
    tempPassword: z.string().min(6).optional(),
    /** If provided, stored as bcrypt password_hash (login via /api/login using password field). */
    permanentPassword: z.string().min(8).optional(),
    fullName: z.string().trim().min(1).optional(),
    whatsapp: z.string().trim().min(8).max(24).optional(),
    /** Optional override; default ["Super Admin"]. */
    roles: z.array(z.string().trim().min(1)).min(1).optional(),
  })
  .refine((d) => (d.permanentPassword ?? "").trim().length > 0 || (d.tempPassword ?? "").trim().length > 0, {
    message: "Either permanentPassword or tempPassword is required",
    path: ["permanentPassword"],
  });

const templeAdminRoleSchema = z.enum([
  "Temple Admin",
  "Head Priest",
  "Trustee",
  "Manager",
  "Accountant",
]);

export const templeAdminProfileBodySchema = z.object({
  sessionEmail: z.string().email(),
  email: z.string().email(),
  fullName: z.string().trim().pipe(z.string().min(1)),
  roles: z.array(templeAdminRoleSchema).min(1),
  phone: z
    .string()
    .trim()
    .pipe(z.string().min(8).max(24)),
});

const templeNested = z
  .object({
    tradition: z.string(),
    name: z.string(),
    deity: z.string(),
    country: z.string(),
    state: z.string().optional(),
    city: z.string(),
    address: z.string(),
    email: z.string(),
    phone: z.unknown(),
    whatsapp: z.unknown(),
    fax: z.unknown(),
    website: z.string(),
    subdomain: z.string(),
    establishedYear: z.string(),
    charityRegistered: z.boolean(),
    charityRegistrationNumber: z.string(),
  })
  .refine(
    (d) => !d.charityRegistered || d.charityRegistrationNumber.trim().length > 0,
    { message: "Charity registration number is required when registered.", path: ["charityRegistrationNumber"] }
  );

const adminNested = z.object({
  fullName: z.string(),
  email: z.string(),
  whatsapp: z.string(),
  role: z.string(),
});

const planBillingNested = z.object({
  selectedPlan: z.string(),
  selectedPricingPlanId: z.string().uuid().optional().nullable(),
  billingCycle: z.string(),
  trial: z
    .object({
      enabled: z.boolean(),
      days: z.number().nullable(),
      endsAt: z.string().nullable().optional(),
    })
    .optional(),
});

export const extendTrialBodySchema = z.object({
  days: z.number().int().min(1).max(365),
});

export const createTempleBodySchema = z.object({
  temple: templeNested,
  admin: adminNested,
  planBilling: planBillingNested,
  logoTempleDataUrl: z.string().nullable().optional(),
  adminProfileDataUrl: z.string().nullable().optional(),
});

const adminNestedUpdate = z.object({
  fullName: z.string(),
  whatsapp: z.string(),
  role: z.string(),
});

export const updateTempleBodySchema = z.object({
  temple: templeNested,
  admin: adminNestedUpdate,
  planBilling: planBillingNested,
  logoTempleDataUrl: z.string().nullable().optional(),
});

/** Slug stored in `master_deities.slug` (temple onboarding primary/sub ids). */
const deitySlugSchema = z.string().trim().min(1).max(64);

export const templeDeitySelectionBodySchema = z
  .object({
    sessionEmail: z.string().email(),
    templeId: z.string().trim().pipe(z.string().min(1)),
    primaryDeityId: deitySlugSchema,
    subDeityIds: z.array(deitySlugSchema).default([]),
    customDeityNote: z.string().max(2000).optional(),
    preferCustomLater: z.boolean().optional(),
  })
  .refine((d) => !d.subDeityIds.includes(d.primaryDeityId), {
    message: "Sub-deities must not include the primary deity.",
    path: ["subDeityIds"],
  })
  .refine((d) => new Set(d.subDeityIds).size === d.subDeityIds.length, {
    message: "Duplicate sub-deity ids are not allowed.",
    path: ["subDeityIds"],
  });

export const templePlanSelectionBodySchema = z.object({
  sessionEmail: z.string().email(),
  templeId: z.string().trim().pipe(z.string().min(1)),
  pricingPlanId: z.string().uuid("Invalid pricing plan id"),
  billing: z.enum(["monthly", "annual"]),
  confirmedAt: z.string().optional(),
});

/** No card fields — strict rejects PAN/CVV/expiry if sent. */
export const templePaymentOnboardingBodySchema = z
  .object({
    sessionEmail: z.string().email(),
    templeId: z.string().trim().pipe(z.string().min(1)),
    saveCardPreferred: z.boolean(),
  })
  .strict();

export const templePaymentSubmissionFieldsSchema = z.object({
  sessionEmail: z.string().email(),
  templeId: z.string().trim().pipe(z.string().min(1)),
  paymentRef: z.string().trim().pipe(z.string().min(1)),
  amountCents: z.coerce.number().int().min(1),
  currency: z.string().trim().pipe(z.string().min(3).max(8)),
  transferredDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Invalid date (expected YYYY-MM-DD)"),
  notes: z.string().optional(),
  invoiceId: z
    .union([z.string().uuid(), z.literal("")])
    .optional()
    .transform((s) => (s === "" || s === undefined ? undefined : s)),
});

export const templeOnboardingCompleteBodySchema = z
  .object({
    sessionEmail: z.string().email(),
    templeId: z.string().trim().pipe(z.string().min(1)),
  })
  .strict();

const phoneRowJsonSchema = z.object({
  countryCode: z.string(),
  nationalNumber: z.string(),
});

const templeFullAddressJsonSchema = z.object({
  countryIso: z.string(),
  state: z.string(),
  city: z.string(),
  postalCode: z.string(),
  street: z.string(),
});

/** PATCH /api/temple-admin/temple-profile/details — foldable section + charity. */
export const templeProfileDetailsPatchBodySchema = z
  .object({
    sessionEmail: z.string().email(),
    websiteUrl: z.string(),
    fax: phoneRowJsonSchema,
    domainSubdomain: z.string(),
    establishedYear: z.string(),
    fullAddress: templeFullAddressJsonSchema,
    logoDataUrl: z.string().nullable(),
    charityRegistered: z.boolean(),
    charityRegistrationNumber: z.string(),
  })
  .refine(
    (d) => !d.charityRegistered || d.charityRegistrationNumber.trim().length > 0,
    { message: "Charity registration number is required when registered.", path: ["charityRegistrationNumber"] }
  );

export const passwordResetRequestBodySchema = z.object({
  email: z.string().email(),
});

export const passwordResetVerifyOtpBodySchema = z.object({
  email: z.string().email(),
  otp: z.string().regex(/^\d{4}$/, "Must be a 4-digit code"),
});

export const passwordResetCompleteBodySchema = z
  .object({
    email: z.string().email(),
    resetToken: z.string().min(32),
    newPassword: z.string().min(8),
    confirmNewPassword: z.string().min(8),
  })
  .refine((d) => d.newPassword === d.confirmNewPassword, {
    message: "Passwords do not match",
    path: ["confirmNewPassword"],
  });

export const createPricingPlanBodySchema = z.object({
  name: z.string().min(1),
  description: z.string().optional(),
  priceMonthly: z.number().int().min(0),
  priceYearly: z.number().int().min(0),
  popular: z.boolean().optional(),
  includedSeats: z.number().int().min(0),
  extraSeatPriceMonthly: z.number().int().min(0),
  features: z.array(z.string()),
});

export const updatePricingPlanBodySchema = createPricingPlanBodySchema
  .partial()
  .refine((data) => Object.keys(data).length > 0, {
    message: "At least one field is required for update",
  });

export const pricingPlanIdParamSchema = z.string().uuid("Invalid pricing plan id");

/** Path/query segment for `temples.tenant_id` (UUID after migration 029). */
export const tenantIdParamSchema = z
  .string()
  .trim()
  .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, "Invalid temple id");

/** Path segment for `public.users.id` (UUID after migration 029). */
export const platformUserIdParamSchema = z
  .string()
  .trim()
  .regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i, "Invalid user id");

/** Path segment: `master_deities.id` (UUID). */
export const masterDeityIdParamSchema = z.string().uuid("Invalid deity id");

export const createMasterDeityBodySchema = z.object({
  name: z.string().trim().min(1).max(200),
  secondaryLabel: z.string().max(200).optional().nullable(),
  isActive: z.boolean().optional().default(true),
  countryCode: z.string().trim().max(8).optional().nullable(),
  placeholderHue: z.string().max(200).optional().nullable(),
  imageDataUrl: z.string().max(15_000_000).optional().nullable(),
  slug: z.string().trim().min(1).max(64).optional().nullable(),
});

export const updateMasterDeityBodySchema = createMasterDeityBodySchema
  .partial()
  .refine((d) => Object.keys(d).length > 0, { message: "At least one field is required" });
